### ISSUE TITLE
Can't get debugging to work

### ISSUE THREAD

**Issue by jradxl** [de-jcup/eclipse-bash-editor#226] opened 2020-10-24 22:37 UTC
I've tried both
Version: 2020-06 (4.16.0)
Build id: 20200615-1200
and 4.17
and Java 8.0.265

Whereas all the editor seems to work and so does run to terminal
But in debug it does not stop at start, nor on a breakpoint. but just runs to end.
The source .../remote-debugging-v2.sh  is being added to the first line of the file.
I know something's listening as in my trials I got a already listing error on starting another instance of Eclipse. (a reboot fixed that)
I'm using Ubuntu 20.04 Focal

I can't see anything in your trouble shooting to help me.
Can you explain more so I can fault find.
Thx

Just to say that Java debugging works. That may not be significant, but just mentioned so you know Eclipse is working and I know how to work it!!

**Comment by MacqGit** [comment] 2021-01-13 13:53
Similar problem here.
I'm running:
Version 2.5.0

The editor is working but when launching a "debug" session, although the ~/.basheditor scripts seem to do their job, the debug just "ignores" the breakpoints and runs throughout the script up until the end.
Sadly, I managed to get it working once correctly (by resetting Eclipse, modifying listening Port,...) but when I tried to relaunch the debug session after having killed it, I couldn't reproduce this correct behavior anymore.
This is what I could collect when launching Eclipse from the terminal:
....
No file found :./PID_debug-terminal_port_33333.txt inside pwd=/home/bernard/.basheditor
/home/bernard/.basheditor/kill-old-terminals-v2.sh: line 5: kill: (5549) - No such process
However, the "PID_debug-terminal_port_33333.txt " was well there...

So it looks to me like there is a mismatch in opening/killing the "remote connection".

Just for info (and sorry if this might be a bit misleading as I'm actually quite new to the Linux environment) the script I'm trying to debug is belonging to USER B, while Eclipse runs under USER A. However, this script belongs to a group shared by USERS A & B.

**Comment by de-jcup** [comment] 2021-02-19 23:57
Hello there - sorry for the very late response. I just release Version 2.6.0 on eclipse marketplace. There the scripts 

```
~/.basheditor/kill-old-terminals-v2.sh
~/.basheditor/remote-debugging-v2.sh
~/.basheditor/store-terminal-pid-v2.sh
```
are now always created/ensured before the terminal launch process is started. So maybe this could handle your problems as well.

The origin issue was here : https://github.com/de-jcup/eclipse-bash-editor/issues/229 
where I had a similar error message: `bash: ./store-terminal-pid-v2.sh: No such file or directory`.

Please give me feedback if this happens with 2.6.0 as well or not.
Thx.

**Comment by de-jcup** [comment] 2021-07-19 06:59
After half year having no repsone anymore , I close this one.

**Closed by de-jcup** 2021-07-19 06:59 UTC
Labels: debugger, support
