### ISSUE TITLE
bash editor freeze completely eclipse IDE

### ISSUE THREAD

**Issue by alef75** [de-jcup/eclipse-bash-editor#206] opened 2020-06-27 13:49 UTC
After update basheditor from v 2.2.3 to 3.3.0 I cant use it anymore:
Every time I open a bash file with basheditor eclipse freeze completely and I need to kill and restart it.
Every time I  click on the bash editor preferences eclipse freeze completely and I need to kill and restart it.

If I downgrade to the previous version than all work great again.

I've got the same behavior  with both eclipse IDE 2020-03 (ubuntu 16.04 and ubuntu 20.04) and eclipse IDE 2020-06 (ubuntu 20.04).
Eclipse hase the followowing plugin:
CDT
PDT
WildWebDeveloper

**Comment by de-jcup** [comment] 2020-06-30 20:20
I think you are talking about the 2.3.0 version.

Is this happening for every bash file? 
Oh moment... you are using `WildWebDeveloper` plugin. There is also a bash editor included in combination with generic editor and a LSP (language server protocol). 

Please do me a favor and uninstall `WildWebDeveloper` plugin (temporarily), restart eclipse and try again...

**Comment by de-jcup** [comment] 2020-06-30 20:33
Forget my former idea about unintalling WildWebDeveloper`  - it has no bash support. Sorry my fault.

But could please add an example where the freeze happens to this issue?

**Comment by de-jcup** [comment] 2020-06-30 21:20
I tried out a fresh installation of Eclipse Java IDE 2020-06 (downloaded as package from eclipse.org) on Linux Mint 19.3 (which is based on Ubuntu 18.x) and installed editor - see next video:
https://youtu.be/avLZb411kT0

I have absolute no problems. Maybe you can share also a video showing up the behaviour? 
It would also be nice to have some error logs from error view showing up some information related to bash editor.

**Comment by alef75** [comment] 2020-06-30 22:16
Thank you for your time.
Yes you are right I'm talking about the 2.3.0 version, (not 3.3.0)
Now I've created a new workspaces from my eclipse 2020-06, with this new workspace all work right.
I've got a tar archive of my workspace that I use as template to start new project.
I've just extracted and opened with eclipse, and with these copy bash editor work right.
I confirm that the problem persist on my current workspace.
it is something related to my current workspace.
 
In my eclipse 2020-03 with bash editor v 2.2.3 all work right as soon as I upgrade to basheditor 2.3.0, 
![basheditor_KO](https://user-images.githubusercontent.com/37915977/86182310-04b4bf00-bb30-11ea-9746-c4b683855da1.png)
the problem appears.
What can I do to collect more information for you ?

**Comment by de-jcup** [comment] 2020-07-01 07:57
#### Okay, first of all let me ensure I fully understand what you described:

1. With your template-workspace (your tar contains a full workspace)
   a) 2020-03: bash editor works
   b) 2020-06: bash editor works not - FREEZE
2. With new workspace
   a) 2020-03: bash editor works
   b) 2020-06: bash editor works

##### Suggestions
Eclipse workspaces are normally converted on startup of newer eclipse version by upgrading workspace version - normally you got a conversion/upgrade message. 

Maybe the problem is in gathering bash workspace meta model - but I am not sure. Inside `$workspaceFolder/.metadata` there are stored information about plugins etc. If you have 

At https://stackoverflow.com/questions/11768106/clean-out-eclipse-workspace-metadata there are some ideas about cleanup workspace. E.g. the "-clean" option can be a good choice.

I would recommend to open your template workspace, let eclipse 2020-06 convert the workspace then exit eclipse, store the "new" template, tar/zip it and try again with the "new" template. This should be 2020-06 compatible.

#### Gathering more information
Please look at https://github.com/de-jcup/eclipse-bash-editor/wiki/FAQ#how-can-i-get-more-information-about-problems

**Comment by alef75** [comment] 2020-07-04 23:40
Let me recap my situations:
and excuse me if I was not so clear.

1) eclipse 2020-03 any workspaces with basheditor V 2.2.3 ---> no problems: all work great
2) eclipse 2020-03 any workspaces with basheditor V 2.3.0 ---> problems: freeze as I open a bash file or click on the basheditor preferences

3) eclipse 2020-06 any workspaces with basheditor V 2.3.0 ---> problems: freeze as I open a bash file or click on the basheditor preferences

I don't know how to try eclipse 2020-06 with basheditor 2.2.3.
The freeze problem had arose as soon I updated bash editor from 2.2.3 to 2.3.0 on my eclipse 2020-03 installation on my ubuntu 16.04 machine.

Some day after, on my ubuntu 20.04 machine I've installed the new eclipse 2020-06 CDT from scratch and I've installed all my usual plugins : PDT,Pydev,wildwebdeveloper,bashscript,cucumber ec... (the same plugin I use in the 2020-03 installation).
In this Installarion, all worked right for some times, but then,at some point the freeze problem arose.

In attachement (eclipseFreeze_jstack.txt) a jstack log taken while eclipse is freezing (I've opened a file .sh).
[eclipseFreeze_jstack.txt](https://github.com/de-jcup/eclipse-bash-editor/files/4874049/eclipseFreeze_jstack.txt)

I've made some tests in order to understand which plungin can cause the problem:
I've uninstalled all the plungins except cdt, but the freeze is here again.

From the same workspace, I've:
1) closed the C project.
2) Opened an external bash script file 
3) the file opened without the freeze and also opening the basheditor preferences works without problem

if I reopen the project and I try to save the opened external bash file, the freeze reappears.
The problem seem related to the project.

I hope this could help to investigate the problem

**Comment by de-jcup** [comment] 2020-07-14 22:38
Hmm.. reading given jstack log there is a lock at the start /activete of bash editor plugin at task support installation phase:
```
"main" #1 prio=6 os_prio=0 tid=0x00007f8b4400c000 nid=0x1faca runnable [0x00007f8b4aa84000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x00000000e85dd148> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <0x00000000e85dd148> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at de.jcup.basheditor.BashFileWithoutExtensionPropertyTester.isFirstLineBashSheBang(BashFileWithoutExtensionPropertyTester.java:71)
	at de.jcup.basheditor.BashTaskTagsSupportProvider.isFileHandled(BashTaskTagsSupportProvider.java:50)
	at de.jcup.eclipse.commons.tasktags.TaskTagsSupport.doNoResourceChangedScan(TaskTagsSupport.java:131)
...
	at de.jcup.eclipse.commons.tasktags.TaskTagsSupport.doNoResourceChangedScan(TaskTagsSupport.java:128)
	at de.jcup.eclipse.commons.tasktags.TaskTagsSupport.noResourceChangedScan(TaskTagsSupport.java:114)
	at de.jcup.eclipse.commons.tasktags.TaskTagsSupport.install(TaskTagsSupport.java:93)
	at de.jcup.basheditor.BashEditorActivator.start(BashEditorActivator.java:71)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:843)
...
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
...
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)

   Locked ownable synchronizers:
	- <0x0000000080640208> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
```


The installation of the task support is done inside main thread. 

Maybe this is the problem. I could  move task support and also model support installations into a background eclipse job.

**Comment by de-jcup** [comment] 2020-07-14 22:54
@alef75 The trace before shows that the lock is done while doing a call to `BashFileWithoutExtensionPropertyTester.isFirstLineBashSheBang`

This happens only, when a file has NO file ending.
Also the trace happens on eclipse start /plugin start

Have you files inside your project having no fileendings?
It would be nice if you could attach a complete example project to this issue - would be easier to test.

**Comment by de-jcup** [comment] 2020-07-22 21:42
@alef75 with last commit I changed the startup behaviour. An own eclipse job is started (so another thread ) doing the model and task support installation. I will close this issue - please do me a favor: When Version 2.4.0 is available on eclipse marketplace (will come soon) please tryout if the problem is solved.

If not... please create another issue and link to this one. (But hopefully this will solve the problem)

**Closed by de-jcup** 2020-07-22 21:42 UTC

**Comment by alef75** [comment] 2020-07-22 22:38
Thank you for working on that.
for sure I will try it as soon as the 2.4.0 will be available and let you know

**Comment by de-jcup** [comment] 2020-08-03 00:17
@alef75 : I just deployed version 2.4.0 to eclipse marketplace. Maybe this version does not longer freeze. Please test and give me some feedback. If there is still a problem there, please create new issue and link this one.

**Comment by alef75** [comment] 2020-08-03 22:27
@de-jcup : I've just updated to 2.4.0 on eclipse 2020-06.For now all work great.
I've only noticed  that there is ans infinite ongoing  task on the eclipse progress view that can't be stopped:
"Install bash editor model and task support".
This doesn't cause any issue in particular.
I'll give you more feedback in the next days

**Comment by alef75** [comment] 2020-08-05 07:32
I,ve made some other test and unfortunately I've found the problem is still present, but it behave in a different way:
it doesn't freeze the UI anymore, but it blocks the build command.
as you suggested me, I'm going to open a new issue
